### ISSUE TITLE
Array index out of bound issue

### ISSUE THREAD

**Issue by hillolsarker** [MD2Korg/cStress_Android#5]
Array index out of bound exceptions in numerous places

examples:

RipQualityCalculation::classifyDataPoints => 
max_value = data[0];
min_value = data[0];
Here data array can be empty

RIPFeatures::rsaCalculateCycle =>
double max = ecg.RRStats.getElement(cInd.get(0));
Here cInd can be empty

**Comment by twhnat** [comment]
This should be reevaluated after the data quality, interpolation, and winsorization code is integrated.  In the mean time, any information you can provide as to why particular instances have no data will be appreciated.

**Comment by twhnat** [comment]
These problems have been corrected by introducing some additional size checks in the code.
